### PR TITLE
Update URLs for new ownership

### PR DESCRIPTION
**Pull request by Finomnis**

### CODE REVIEW

**Review by mciantyre — APPROVED** [review]
LGTM. Happy to see that the old links find their way here, too.

**Comment by Finomnis** [comment]
@mciantyre will you create a release tag and a release, to try out the release workflow?

**Comment by mciantyre** [comment]
0.1.2 is on crates.io. Thanks for setting all this up!

**Comment by Finomnis** [comment]
Welcome, it's a pleasure :)

**Pull request merged**
